version: 0.2

phases:
  install:
    commands:
      - cd frontend && npm install
  build:
    commands:
      - npm run build  # Builds the project
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build  # Directory with output files (e.g., React app)
